import { Post, MarketplaceItem, User } from '../types';

export const INITIAL_USER: User = {
  id: 'user-ahmed-1',
  name: 'Ahmed Khan',
  email: 'ahmed.khan@uog.edu.pk',
  university: 'UOG',
  batch: 'Batch 2026',
  whatsapp: '923005551234',
  avatarBg: '#17243A',
  createdAt: '2025-09-10T10:00:00Z',
};

export const INITIAL_POSTS: Post[] = [
  {
    id: 'post-1',
    authorId: 'user-ahmed-1',
    authorName: 'Ahmed Khan',
    authorUniversity: 'UOG',
    authorBatch: 'Batch 2026',
    title: 'Which CS electives are worth taking in 5th semester at UOG Islamabad?',
    content: `I'm finalizing course registration for the upcoming semester and torn between Advanced Programming, Web Development, and Theory of Automata prerequisites.

For students who have already taken AP under Dr. Farooq or Web under Sir Usman:
1. What is the assignment workload like per week?
2. Which elective gives practical project experience that translates well into summer internships?
3. How fair are the grading curves?

Appreciate any honest advice before the portal closes this Friday!`,
    category: 'Course Review',
    reactions: { Relatable: 5, Helpful: 24, Support: 2, Vibe: 0 },
    commentCount: 5,
    createdAt: '2 hours ago',
    userReaction: undefined,
    isSaved: true,
    comments: [
      {
        id: 'c-1',
        postId: 'post-1',
        authorId: 'user-2',
        authorName: 'Usman Ali',
        authorUniversity: 'UOG',
        content: 'AP is heavy on C++ memory management and design patterns. Tough midterm, but makes interviews ridiculously easy later.',
        createdAt: '1 hour ago',
      },
      {
        id: 'c-2',
        postId: 'post-1',
        authorId: 'user-3',
        authorName: 'Sana Tariq',
        authorUniversity: 'UOG',
        content: 'Take Web Dev if you want a complete portfolio project by December. The sprint deadline style mimics real dev shops.',
        createdAt: '45 mins ago',
      },
      {
        id: 'c-3',
        postId: 'post-1',
        authorId: 'user-4',
        authorName: 'Hamza Malik',
        authorUniversity: 'UOG',
        content: 'Avoid taking both AP and DAA together unless you enjoy living in the CS lab past 8 PM.',
        createdAt: '20 mins ago',
      },
    ],
  },
  {
    id: 'post-2',
    authorId: 'user-5',
    authorName: 'Zainab Shah',
    authorUniversity: 'ILM',
    authorBatch: 'Batch 2025',
    title: 'SEECS Final Year Project guidelines & industry liaison tips for 2026',
    content: `For juniors in SEECS entering 7th semester: Do NOT pick a FYP topic purely because it sounds fancy in an abstract. Start talking to prospective advisors in July.

Key takeaways from our batch:
- Industry-partnered projects often get prototype grants and direct job pipelines.
- Ensure all 3 group members have balanced commitments (avoid teaming up with friends who plan to skip lab sprints).
- Get your problem statement approved by week 3 or you will be scrambling at the proposal defense.`,
    category: 'General',
    reactions: { Relatable: 12, Helpful: 42, Support: 8, Vibe: 5 },
    commentCount: 4,
    createdAt: '5 hours ago',
    userReaction: 'Helpful',
    isSaved: false,
    comments: [
      {
        id: 'c-4',
        postId: 'post-2',
        authorId: 'user-6',
        authorName: 'Bilal Qureshi',
        authorUniversity: 'ILM',
        content: 'Solid advice. Our group secured an industry grant from a local fintech because we pitched a working MVP early.',
        createdAt: '3 hours ago',
      },
      {
        id: 'c-5',
        postId: 'post-2',
        authorId: 'user-7',
        authorName: 'Ayesha Raza',
        authorUniversity: 'ILM',
        content: 'Which lab coordinators in SEECS are most supportive regarding hardware GPU allocations?',
        createdAt: '1 hour ago',
      },
    ],
  },
  {
    id: 'post-3',
    authorId: 'user-8',
    authorName: 'Muneeb Arshad',
    authorUniversity: 'Superior',
    authorBatch: 'Batch 2026',
    title: 'Superior Islamabad Park Road route: private vans vs university transport schedule',
    content: `Starting next week, evening lab batches end at 5:15 PM. The university buses on the Rawalpindi / Saddar route fill up in under 5 minutes.

Anyone currently carpooling from Satellite Town or Westridge? Looking to split petrol costs for 3 days a week. Drop a comment if you have an open seat.`,
    category: 'General',
    reactions: { Relatable: 18, Helpful: 2, Support: 10, Vibe: 1 },
    commentCount: 3,
    createdAt: 'Yesterday',
    userReaction: undefined,
    isSaved: false,
    comments: [
      {
        id: 'c-6',
        postId: 'post-3',
        authorId: 'user-9',
        authorName: 'Talha Bin Tariq',
        authorUniversity: 'Superior',
        content: 'I commute from Chandni Chowk daily around 7:45 AM. Have 2 seats open. DM me on WhatsApp.',
        createdAt: 'Yesterday',
      },
    ],
  },
  {
    id: 'post-4',
    authorId: 'user-10',
    authorName: 'Hira Mustafa',
    authorUniversity: 'UOP',
    authorBatch: 'Batch 2027',
    title: 'UOP University E-9 campus: Midterm preparation strategy for Digital Logic Design',
    content: `Professors have released the syllabus for DLD midterms (Boolean algebra, K-Maps, and combinational circuit decoders).

Are the class slides sufficient, or do the exam papers usually pull numerical problems from Morris Mano Chapter 4? Would love insights from 2nd year seniors.`,
    category: 'Course Review',
    reactions: { Relatable: 5, Helpful: 15, Support: 3, Vibe: 0 },
    commentCount: 2,
    createdAt: '1 day ago',
    userReaction: undefined,
    isSaved: false,
    comments: [
      {
        id: 'c-7',
        postId: 'post-4',
        authorId: 'user-11',
        authorName: 'Daniyal Javed',
        authorUniversity: 'UOP',
        content: 'Definitely practice the exercise problems from Morris Mano 5th edition. At least two questions are identical to book end-problems.',
        createdAt: '18 hours ago',
      },
    ],
  },
  {
    id: 'post-5',
    authorId: 'user-12',
    authorName: 'Saad Farooq',
    authorUniversity: 'UOC',
    authorBatch: 'Batch 2025',
    title: 'UOC University E-8: Admission test cutoffs and merit list expectations for Fall',
    content: `Compiling merit expectations for friends applying to CS and Software Engineering at UOC Islamabad.

Past trend:
- 1st merit list aggregate for CS was approx 71.5%
- 2nd list dropped to around 68.2%
If your aggregate is above 72%, you are in a safe zone for morning session.`,
    category: 'Admissions',
    reactions: { Relatable: 3, Helpful: 29, Support: 12, Vibe: 4 },
    commentCount: 4,
    createdAt: '2 days ago',
    userReaction: undefined,
    isSaved: false,
    comments: [
      {
        id: 'c-8',
        postId: 'post-5',
        authorId: 'user-13',
        authorName: 'Maryam Noor',
        authorUniversity: 'UOC',
        content: 'Does UOC give preference to NTS-NAT over their own internal computer test?',
        createdAt: '1 day ago',
      },
      {
        id: 'c-9',
        postId: 'post-5',
        authorId: 'user-12',
        authorName: 'Saad Farooq',
        authorUniversity: 'UOC',
        content: 'Both are treated equally in percentage calculation, but internal test math portion is slightly more predictable.',
        createdAt: '1 day ago',
      },
    ],
  },
];

export const INITIAL_MARKETPLACE: MarketplaceItem[] = [
  {
    id: 'market-1',
    sellerId: 'user-ahmed-1',
    sellerName: 'Ahmed Khan',
    sellerWhatsapp: '923005551234',
    title: 'Calculus I & II Handwritten Master Notes + Solved Midterms',
    courseName: 'Calculus & Analytical Geometry',
    courseCode: 'MTH101',
    university: 'UOG',
    price: 0,
    description: 'Complete set of scanned handwritten notes covering differentiation, integration techniques, Taylor series, and 5 years of solved UOG midterms. Clean handwriting with annotated step-by-step proofs.',
    driveLink: 'https://drive.google.com/drive/folders/sample-calculus-notes',
    coverImage: '/src/assets/images/calculus_notes_cover_1790333468648.jpg',
    createdAt: '3 hours ago',
  },
  {
    id: 'market-2',
    sellerId: 'user-5',
    sellerName: 'Zainab Shah',
    sellerWhatsapp: '923129876543',
    title: 'Data Structures & Algorithms Coursepack + LeetCode Roadmap',
    courseName: 'Data Structures',
    courseCode: 'CS201',
    university: 'ILM',
    price: 0,
    description: 'Concise review guides for Linked Lists, Trees, Heaps, AVL Trees, Graphs (Dijkstra, BFS/DFS) and dynamic programming basics. Includes past SEECS quizzes and practice problem sheets.',
    driveLink: 'https://drive.google.com/drive/folders/sample-dsa-notes',
    coverImage: '/src/assets/images/data_structures_notes_1790333482318.jpg',
    createdAt: '1 day ago',
  },
  {
    id: 'market-3',
    sellerId: 'user-8',
    sellerName: 'Muneeb Arshad',
    sellerWhatsapp: '923334567890',
    title: 'Database System Concepts (Silberschatz) 7th Ed. Hardcover',
    courseName: 'Database Systems',
    courseCode: 'CS304',
    university: 'Superior',
    price: 1500,
    description: 'Original physical book in pristine condition. No pen marks or highlights inside. Pick up from Superior Islamabad main gate or H-13 hostel area. Saves paying 3500 PKR at F-10 bookshops.',
    coverImage: '/src/assets/images/database_systems_book_1790333494400.jpg',
    createdAt: '2 days ago',
  },
  {
    id: 'market-4',
    sellerId: 'user-10',
    sellerName: 'Hira Mustafa',
    sellerWhatsapp: '923214433221',
    title: 'Digital Logic Design Lab Manuals & Multisim Circuit Files',
    courseName: 'Digital Logic Design',
    courseCode: 'EE200',
    university: 'UOP',
    price: 350,
    description: 'Includes lab reports for experiments 1 through 10, pre-lab calculations, and verified Multisim .ms14 simulation project files for decoder circuits and ripple counters.',
    driveLink: 'https://drive.google.com/drive/folders/sample-dld-manuals',
    createdAt: '3 days ago',
  },
  {
    id: 'market-5',
    sellerId: 'user-12',
    sellerName: 'Saad Farooq',
    sellerWhatsapp: '923458877665',
    title: 'Discrete Mathematics Rosen 8th Edition Lecture Summaries',
    courseName: 'Discrete Structures',
    courseCode: 'MTH202',
    university: 'UOC',
    price: 0,
    description: 'Summary sheets for propositional logic, set theory, graph coloring, and recurrence relations. Formatted specifically for UOC syllabus.',
    driveLink: 'https://drive.google.com/drive/folders/sample-discrete-math',
    createdAt: '4 days ago',
  },
  {
    id: 'market-6',
    sellerId: 'user-3',
    sellerName: 'Sana Tariq',
    sellerWhatsapp: '923021122334',
    title: 'Computer Networks Top-Down Approach (Kurose & Ross) + Wireshark Labs',
    courseName: 'Computer Networks',
    courseCode: 'CS307',
    university: 'UOG',
    price: 600,
    description: 'Paperback copy plus printed solutions for Wireshark labs (TCP/UDP, HTTP headers, DNS analysis). Available on UOG H-9 campus.',
    createdAt: '5 days ago',
  },
];

